name: mav
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/2t34lth/mav

environment:
  sdk: ^3.3.0

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
